### ISSUE TITLE
[ISSUE] Block-Breaking Data IDs Don't Do Anything?

### ISSUE THREAD

**Issue by JoeDon16** [JCulley/ProQuests-Documentaion#28]
Spigot Profile: https://www.spigotmc.org/members/joedon16.126780/
Spigot Version: 1.8.8
Error: no error in Console or anything from ProQuests

Setting up a Block-Breaking quests, works great. When I try to set an allowed block with an ID(so that that block is the only one that counts towards the total count), nothing works. I'm using NETHER_STALK;3 currently, which is the full grown state of netherwart, but it doesn't work at all (no block adds on to the count). My config:

https://hastebin.com/zudovuluxu.bash

I've also messed around the the required blocks thingy, but it's the same thing.

**Comment by JCulley** [comment]
That simply means that the data value of the item that is broken does not match that of which is defined in the quest. This is due to the fact that although the full grown state maintains a data value of 3 once broken it has a value of 0. So it is only checking the data value of 0. The only time it works accordingly is when the material and block have the same data value. There’s nothing I can do about this. For specific quests like these you should use a delivery or obtain quests as you are trying to get the player to retrieve a specific item, not break blocks.
