### ISSUE TITLE
This plugin isn't detailed enough for me, or either broken, so I need help.

### ISSUE THREAD

**Issue by flrping** [JCulley/ProQuests-Documentaion#46]
Account: https://www.spigotmc.org/members/flrping.238558/
Ver: 1.8.8
No errors in console.. soo I dont really need a link.
https://imgur.com/a/qIFXN

This.. is annoying. I try numbers, the name, etc. Doesn't work. Invalid.
If Im doing something wrong, let me know and tell me how to fix it. Really not liking this plugin so far.
Checked the wiki page, that you told me to. Didn't find anything related so, making something here

**Comment by JCulley** [comment]
If the guidelines ask for a log you should provide it don’t you think. Regardless numeric ids are deprecated as of Spigot 1.8 which is why this plugin DOES NOT use numeric ids and no plugins should. Use the material enum values https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html. Lastly if you open another issue without any sufficient information it will more than likely be closed immediately.

**Comment by Devillion** [comment]
@flrping Just because there are no proquests errors that you can see, sometimes the startup logs can show the author clues for why your having issues.
